# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad72f5b7b5dd67e9604b0650dd89a17fd195f3415f7c68610290894bc02651d51d5db050af57c7e065b723dbbfd5dbb8b50cac4eb5252f1c5d3846bcdddd5b5

test:
  secret_key_base: 0ef5571b673e2d442d2400dfc54d5f8fc38cd65b0facf786d1da0a84da2286d0e0b42df4e33cbe8106b088532fe5a1d9ef1c51e6f655948a76e465d7e7fbd30c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
